apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: mck-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: mck-demo
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/Mpluya/mck-demo
      ref:
        branch: main
